//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/VFXApprentice/Sandbox/Gameplay/InputSystem/SidescrollerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @SidescrollerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @SidescrollerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""SidescrollerInputActions"",
    ""maps"": [
        {
            ""name"": ""PlayerActionMap"",
            ""id"": ""b3991e0d-380d-498d-94e6-b951195d8b38"",
            ""actions"": [
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""70608c08-2978-4bfa-a383-a1bc0d0bded3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""a360f3f2-12b2-49f5-8791-dc75a8b9e983"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""e038480d-f2c0-4b74-aeea-9bbb130cdb69"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""8ea8b33a-f871-495e-b023-a74a50c898c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectAttack1"",
                    ""type"": ""Button"",
                    ""id"": ""06df0fc6-5e3b-4b06-91e9-a9f0cbbc99f5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectAttack2"",
                    ""type"": ""Button"",
                    ""id"": ""614dcd44-9926-4784-be56-1c7c9c14b45b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectAttack3"",
                    ""type"": ""Button"",
                    ""id"": ""c0283caa-5d96-484d-a023-4191f660433e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectNextAttack"",
                    ""type"": ""Button"",
                    ""id"": ""75983699-f535-4f90-bda0-2092a8c55610"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""caeb72b8-47b0-45fd-ac75-c55c6f2f5c4c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8c6fd4c-5784-44a2-8504-506b02e5b9f0"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAttack1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d757b31-ce5d-4441-a3a3-c308a23eace6"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAttack2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1c4af50-5547-480f-bde0-55de9ab1f9c1"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAttack3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""145f99c1-b823-4aff-b73c-04a06e05e69f"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a30f6487-2459-4542-8e0e-0676c312fe5c"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""613e5f32-2910-428a-9d12-4255b32d7318"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""AD"",
                    ""id"": ""076fc7c8-8b41-4e00-9ca9-87a65f44ac94"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""e943bb54-56ab-444b-a694-69790cc1cf1c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""7f1fbd1f-50f1-41bc-83cb-d778455acc2e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""76fca6cd-31d8-48f7-a4c5-a3b5db34a1a9"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""e1e352f6-5148-491f-a839-4cac44206eba"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""f56c6752-e3c2-47e4-9905-dec97956e397"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""42e4204a-5edc-4722-a364-8060e17d446c"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectNextAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerActionMap
        m_PlayerActionMap = asset.FindActionMap("PlayerActionMap", throwIfNotFound: true);
        m_PlayerActionMap_MousePosition = m_PlayerActionMap.FindAction("MousePosition", throwIfNotFound: true);
        m_PlayerActionMap_Move = m_PlayerActionMap.FindAction("Move", throwIfNotFound: true);
        m_PlayerActionMap_Jump = m_PlayerActionMap.FindAction("Jump", throwIfNotFound: true);
        m_PlayerActionMap_Attack = m_PlayerActionMap.FindAction("Attack", throwIfNotFound: true);
        m_PlayerActionMap_SelectAttack1 = m_PlayerActionMap.FindAction("SelectAttack1", throwIfNotFound: true);
        m_PlayerActionMap_SelectAttack2 = m_PlayerActionMap.FindAction("SelectAttack2", throwIfNotFound: true);
        m_PlayerActionMap_SelectAttack3 = m_PlayerActionMap.FindAction("SelectAttack3", throwIfNotFound: true);
        m_PlayerActionMap_SelectNextAttack = m_PlayerActionMap.FindAction("SelectNextAttack", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerActionMap
    private readonly InputActionMap m_PlayerActionMap;
    private IPlayerActionMapActions m_PlayerActionMapActionsCallbackInterface;
    private readonly InputAction m_PlayerActionMap_MousePosition;
    private readonly InputAction m_PlayerActionMap_Move;
    private readonly InputAction m_PlayerActionMap_Jump;
    private readonly InputAction m_PlayerActionMap_Attack;
    private readonly InputAction m_PlayerActionMap_SelectAttack1;
    private readonly InputAction m_PlayerActionMap_SelectAttack2;
    private readonly InputAction m_PlayerActionMap_SelectAttack3;
    private readonly InputAction m_PlayerActionMap_SelectNextAttack;
    public struct PlayerActionMapActions
    {
        private @SidescrollerInputActions m_Wrapper;
        public PlayerActionMapActions(@SidescrollerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MousePosition => m_Wrapper.m_PlayerActionMap_MousePosition;
        public InputAction @Move => m_Wrapper.m_PlayerActionMap_Move;
        public InputAction @Jump => m_Wrapper.m_PlayerActionMap_Jump;
        public InputAction @Attack => m_Wrapper.m_PlayerActionMap_Attack;
        public InputAction @SelectAttack1 => m_Wrapper.m_PlayerActionMap_SelectAttack1;
        public InputAction @SelectAttack2 => m_Wrapper.m_PlayerActionMap_SelectAttack2;
        public InputAction @SelectAttack3 => m_Wrapper.m_PlayerActionMap_SelectAttack3;
        public InputAction @SelectNextAttack => m_Wrapper.m_PlayerActionMap_SelectNextAttack;
        public InputActionMap Get() { return m_Wrapper.m_PlayerActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActionMapActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActionMapActions instance)
        {
            if (m_Wrapper.m_PlayerActionMapActionsCallbackInterface != null)
            {
                @MousePosition.started -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnMousePosition;
                @MousePosition.performed -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnMousePosition;
                @MousePosition.canceled -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnMousePosition;
                @Move.started -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnJump;
                @Attack.started -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnAttack;
                @SelectAttack1.started -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnSelectAttack1;
                @SelectAttack1.performed -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnSelectAttack1;
                @SelectAttack1.canceled -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnSelectAttack1;
                @SelectAttack2.started -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnSelectAttack2;
                @SelectAttack2.performed -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnSelectAttack2;
                @SelectAttack2.canceled -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnSelectAttack2;
                @SelectAttack3.started -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnSelectAttack3;
                @SelectAttack3.performed -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnSelectAttack3;
                @SelectAttack3.canceled -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnSelectAttack3;
                @SelectNextAttack.started -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnSelectNextAttack;
                @SelectNextAttack.performed -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnSelectNextAttack;
                @SelectNextAttack.canceled -= m_Wrapper.m_PlayerActionMapActionsCallbackInterface.OnSelectNextAttack;
            }
            m_Wrapper.m_PlayerActionMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MousePosition.started += instance.OnMousePosition;
                @MousePosition.performed += instance.OnMousePosition;
                @MousePosition.canceled += instance.OnMousePosition;
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @SelectAttack1.started += instance.OnSelectAttack1;
                @SelectAttack1.performed += instance.OnSelectAttack1;
                @SelectAttack1.canceled += instance.OnSelectAttack1;
                @SelectAttack2.started += instance.OnSelectAttack2;
                @SelectAttack2.performed += instance.OnSelectAttack2;
                @SelectAttack2.canceled += instance.OnSelectAttack2;
                @SelectAttack3.started += instance.OnSelectAttack3;
                @SelectAttack3.performed += instance.OnSelectAttack3;
                @SelectAttack3.canceled += instance.OnSelectAttack3;
                @SelectNextAttack.started += instance.OnSelectNextAttack;
                @SelectNextAttack.performed += instance.OnSelectNextAttack;
                @SelectNextAttack.canceled += instance.OnSelectNextAttack;
            }
        }
    }
    public PlayerActionMapActions @PlayerActionMap => new PlayerActionMapActions(this);
    public interface IPlayerActionMapActions
    {
        void OnMousePosition(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnSelectAttack1(InputAction.CallbackContext context);
        void OnSelectAttack2(InputAction.CallbackContext context);
        void OnSelectAttack3(InputAction.CallbackContext context);
        void OnSelectNextAttack(InputAction.CallbackContext context);
    }
}
